// ── Tournament configuration by tour and surface ──────────────────────────────
// Each entry: { name, cpr } — name must match exactly what backend COURT_CPR expects.
export const TOURNAMENT_CONFIG = {
  ATP: {
    Hard: [
      { name: "Australian Open",                  cpr: 40 },
      { name: "US Open",                           cpr: 37 },
      { name: "Indian Wells Masters",              cpr: 36 },
      { name: "Miami Open",                        cpr: 35 },
      { name: "Cincinnati Masters",                cpr: 36 },
      { name: "Canadian Open (Montreal/Toronto)",  cpr: 35 },
      { name: "Vienna Open",                       cpr: 38 },
      { name: "Swiss Indoors Basel",               cpr: 39 },
      { name: "Rotterdam Open",                    cpr: 38 },
      { name: "Qatar Open Doha",                   cpr: 36 },
      { name: "Dubai Duty Free Championships",     cpr: 37 },
      { name: "ATP Finals Turin",                  cpr: 38 },
      { name: "Dallas Open",                       cpr: 37 },
      { name: "Delray Beach Open",                 cpr: 37 },
      { name: "Adelaide International",            cpr: 38 },
      { name: "Auckland Open",                     cpr: 37 },
      { name: "Acapulco Open",                     cpr: 38 },
      { name: "Washington Citi Open",              cpr: 37 },
      { name: "Winston-Salem Open",                cpr: 36 },
      { name: "Tokyo Japan Open",                  cpr: 38 },
      { name: "Shanghai Masters",                  cpr: 36 },
      { name: "Paris Masters",                     cpr: 39 },
      { name: "Stockholm Open",                    cpr: 39 },
      { name: "Antwerp European Open",             cpr: 39 },
      { name: "Challenger Hard (Generic)",         cpr: 33 },
    ],
    Clay: [
      { name: "Roland Garros",                           cpr: 24 },
      { name: "Monte Carlo Masters",                     cpr: 25 },
      { name: "Madrid Open",                             cpr: 29 },
      { name: "Barcelona Open",                          cpr: 24 },
      { name: "Italian Open Rome",                       cpr: 24 },
      { name: "Hamburg Open",                            cpr: 25 },
      { name: "Lyon Open",                               cpr: 25 },
      { name: "Buenos Aires Open",                       cpr: 25 },
      { name: "Rio Open",                                cpr: 26 },
      { name: "Santiago Open",                           cpr: 24 },
      { name: "Houston Clay",                            cpr: 27 },
      { name: "Munich Open",                             cpr: 28 },
      { name: "Estoril Open",                            cpr: 27 },
      { name: "Marrakech Open",                          cpr: 24 },
      { name: "Bastad Open",                             cpr: 24 },
      { name: "Umag Open",                               cpr: 23 },
      { name: "Gstaad Open",                             cpr: 24 },
      { name: "Kitzbuhel Open",                          cpr: 24 },
      { name: "Challenger Clay Europe (Generic)",        cpr: 23 },
      { name: "Challenger Clay South America (Generic)", cpr: 24 },
      { name: "Bordeaux Challenger",                     cpr: 23 },
      { name: "Braunschweig Challenger",                 cpr: 23 },
      { name: "Valencia Challenger",                     cpr: 24 },
      { name: "Monza Challenger",                        cpr: 23 },
      { name: "Aix-en-Provence Challenger",              cpr: 24 },
      { name: "Sanremo Challenger",                      cpr: 23 },
      { name: "Geneva Challenger",                       cpr: 24 },
    ],
    Grass: [
      { name: "Wimbledon",               cpr: 43 },
      { name: "Queens Club Championships", cpr: 44 },
      { name: "Halle",                   cpr: 44 },
      { name: "Stuttgart Grass",         cpr: 42 },
      { name: "Eastbourne International", cpr: 41 },
      { name: "Mallorca Championships",  cpr: 42 },
      { name: "Hertogenbosch Open",      cpr: 43 },
      { name: "Ilkley Challenger",       cpr: 40 },
      { name: "Nottingham Challenger",   cpr: 41 },
    ],
  },

  WTA: {
    Hard: [
      { name: "Australian Open WTA",      cpr: 38 },
      { name: "US Open WTA",              cpr: 36 },
      { name: "Indian Wells WTA",         cpr: 35 },
      { name: "Miami Open WTA",           cpr: 34 },
      { name: "Cincinnati WTA",           cpr: 35 },
      { name: "Canadian Open WTA",        cpr: 34 },
      { name: "Wuhan Open",               cpr: 36 },
      { name: "China Open Beijing",       cpr: 36 },
      { name: "WTA Finals",               cpr: 37 },
      { name: "Dubai WTA",                cpr: 36 },
      { name: "Doha WTA",                 cpr: 35 },
      { name: "Adelaide WTA",             cpr: 37 },
      { name: "Auckland WTA",             cpr: 36 },
      { name: "Acapulco WTA",             cpr: 37 },
      { name: "San Jose WTA",             cpr: 36 },
      { name: "Washington WTA",           cpr: 36 },
      { name: "Tokyo Pan Pacific",        cpr: 37 },
      { name: "Osaka WTA",                cpr: 36 },
      { name: "Linz WTA",                 cpr: 38 },
      { name: "Guadalajara WTA",          cpr: 36 },
      { name: "WTA 125 Hard (Generic)",   cpr: 32 },
      { name: "Austin WTA 125",           cpr: 32 },
      { name: "Jiangxi Open WTA 125",     cpr: 32 },
    ],
    Clay: [
      { name: "Roland Garros WTA",              cpr: 23 },
      { name: "Madrid Open WTA",                cpr: 28 },
      { name: "Italian Open WTA Rome",          cpr: 23 },
      { name: "Stuttgart WTA",                  cpr: 27 },
      { name: "Hamburg WTA",                    cpr: 24 },
      { name: "Prague Open WTA",                cpr: 24 },
      { name: "Rabat WTA",                      cpr: 23 },
      { name: "Strasbourg WTA",                 cpr: 24 },
      { name: "Warsaw WTA",                     cpr: 24 },
      { name: "Budapest WTA",                   cpr: 23 },
      { name: "Bastad WTA",                     cpr: 23 },
      { name: "Palermo WTA",                    cpr: 23 },
      { name: "San Jose Clay WTA",              cpr: 25 },
      { name: "Bogota WTA",                     cpr: 23 },
      { name: "Trophee Clarins Paris WTA 125",  cpr: 23 },
      { name: "Catalonia Open WTA 125",         cpr: 23 },
      { name: "Huzhou Open WTA 125 Clay",       cpr: 23 },
      { name: "Emilia-Romagna WTA 125 Clay",    cpr: 23 },
      { name: "WTA 125 Clay (Generic)",         cpr: 23 },
    ],
    Grass: [
      { name: "Wimbledon WTA",           cpr: 42 },
      { name: "Eastbourne WTA",          cpr: 40 },
      { name: "Birmingham WTA",          cpr: 41 },
      { name: "Hertogenbosch WTA",       cpr: 42 },
      { name: "Mallorca WTA",            cpr: 41 },
      { name: "Ilkley WTA 125 Grass",    cpr: 39 },
    ],
  },
}

// Legacy flat list (kept for backward compat with any other component using it)
export const COURTS_BY_SURFACE = {
  Hard:  ['Australian Open','US Open','Indian Wells Masters','Miami Open','Cincinnati Masters',
          'Canadian Open (Montreal/Toronto)','Vienna Open','Swiss Indoors Basel','Rotterdam Open',
          'Qatar Open Doha','Dubai Duty Free Championships','ATP Finals Turin'],
  Clay:  ['Roland Garros','Monte Carlo Masters','Madrid Open','Barcelona Open','Italian Open Rome',
          'Hamburg Open','Lyon Open'],
  Grass: ['Wimbledon','Queens Club Championships','Halle','Stuttgart Grass','Eastbourne International'],
}

export const ATP_AVERAGES = {
  aces: 10.0, double_faults: 3.0,
  first_serve_pct: 65.0, first_serve_pts_won: 75.0,
  second_serve_pts_won: 55.0, return_first_serve_pts_won: 32.0,
  return_second_serve_pts_won: 53.0, bp_converted: 45.0, bp_saved: 65.0,
}

export const WTA_AVERAGES = {
  aces: 2.0, double_faults: 4.0,
  first_serve_pct: 62.0, first_serve_pts_won: 65.0,
  second_serve_pts_won: 50.0, return_first_serve_pts_won: 38.0,
  return_second_serve_pts_won: 56.0, bp_converted: 42.0, bp_saved: 60.0,
}

export const SURFACE_COLORS = { Hard: '#42A5F5', Clay: '#EF6C00', Grass: '#2E7D32' }

export const STAT_LABELS = {
  aces: 'Aces / Match',
  double_faults: 'Double Faults / Match',
  first_serve_pct: '1st Serve %',
  first_serve_pts_won: '1st Serve Pts Won',
  second_serve_pts_won: '2nd Serve Pts Won',
  return_first_serve_pts_won: 'Ret Pts Won (1st Srv)',
  return_second_serve_pts_won: 'Ret Pts Won (2nd Srv)',
  bp_converted: 'BP Converted %',
  bp_saved: 'BP Saved %',
}

export const fmt = (v, d = 1) => v == null ? '—' : Number(v).toFixed(d)
export const fmtPct = (v) => v == null ? '—' : `${Number(v).toFixed(0)}%`
